# Generated by Django 5.2.3 on 2026-03-24 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='avatar URL')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='biography')),
                ('level_tennis', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='tennis level')),
                ('level_padel', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='padel level')),
                ('preferred_play_mode', models.CharField(choices=[('friendly', 'Friendly'), ('competitive', 'Competitive'), ('both', 'Both')], default='both', max_length=20, verbose_name='preferred play mode')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('availability', models.JSONField(blank=True, default=dict, null=True, verbose_name='availability')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'player profile',
                'verbose_name_plural': 'player profiles',
                'db_table': 'player_profiles',
            },
        ),
    ]
