# Generated by Django 5.2.3 on 2026-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expo push token'),
        ),
    ]
