# Generated by Django 5.2.3 on 2026-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username'),
        ),
    ]
