# Generated by Django 5.2.3 on 2026-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_connection'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['city'], name='idx_profile_city'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['level_tennis'], name='idx_profile_tennis'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['level_padel'], name='idx_profile_padel'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['username'], name='idx_profile_username'),
        ),
    ]
