# Generated by Django 5.2.3 on 2026-03-26 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_add_connection'),
        ('venues', '0002_timeslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('event_type', models.CharField(choices=[('cup', 'Cup'), ('social', 'Social'), ('clinic', 'Clinic'), ('other', 'Other')], default='cup', max_length=20, verbose_name='event type')),
                ('sport', models.CharField(blank=True, choices=[('tennis', 'Tennis'), ('padel', 'Padel')], max_length=20, null=True, verbose_name='sport')),
                ('date', models.DateField(verbose_name='date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('max_attendees', models.IntegerField(blank=True, null=True, verbose_name='max attendees')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='registration deadline')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='price')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='image URL')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venue', verbose_name='venue')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'events',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted')], default='registered', max_length=20, verbose_name='status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='event')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_partner_registrations', to='accounts.playerprofile', verbose_name='partner')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='accounts.playerprofile', verbose_name='player')),
            ],
            options={
                'verbose_name': 'event registration',
                'verbose_name_plural': 'event registrations',
                'db_table': 'event_registrations',
                'ordering': ['registered_at'],
                'unique_together': {('event', 'player')},
            },
        ),
    ]
