web: python manage.py migrate --noinput; python manage.py collectstatic --noinput; daphne -b 0.0.0.0 -p $PORT gomatch_api.asgi:application --verbosity 1
worker: celery -A gomatch_api worker -l info --concurrency 4
beat: celery -A gomatch_api beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
