# Generated by Django 5.2.3 on 2026-03-24 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_playerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('tennis', 'Tennis'), ('padel', 'Padel')], max_length=20, verbose_name='sport')),
                ('match_type', models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles')], max_length=20, verbose_name='match type')),
                ('play_mode', models.CharField(choices=[('friendly', 'Friendly'), ('competitive', 'Competitive'), ('both', 'Both')], max_length=20, verbose_name='play mode')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('scheduled_date', models.DateField(verbose_name='scheduled date')),
                ('scheduled_time', models.TimeField(verbose_name='scheduled time')),
                ('max_participants', models.IntegerField(verbose_name='max participants')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'db_table': 'matches',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('invited', 'Invited'), ('joined', 'Joined')], max_length=20, verbose_name='role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('left', 'Left')], default='pending', max_length=20, verbose_name='status')),
                ('team', models.CharField(blank=True, choices=[('team_a', 'Team A'), ('team_b', 'Team B')], max_length=10, null=True, verbose_name='team side')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.match', verbose_name='match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='accounts.playerprofile', verbose_name='player')),
            ],
            options={
                'verbose_name': 'match participant',
                'verbose_name_plural': 'match participants',
                'db_table': 'match_participants',
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'scheduled_date'], name='idx_match_status_date'),
        ),
        migrations.AlterUniqueTogether(
            name='matchparticipant',
            unique_together={('match', 'player')},
        ),
    ]
