# Generated by Django 5.2.3 on 2026-03-24 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_level_min', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='minimum skill level')),
                ('required_level_max', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True, verbose_name='maximum skill level')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='description')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_match', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'open match',
                'verbose_name_plural': 'open matches',
                'db_table': 'open_matches',
                'ordering': ['-match__scheduled_date'],
            },
        ),
    ]
