# Generated by Django 5.2.3 on 2026-03-24 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_playerprofile'),
        ('matches', '0002_openmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sets', models.JSONField(help_text='Example: [{"team_a": 6, "team_b": 4}, {"team_a": 3, "team_b": 6}]', verbose_name='sets')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_scores', to=settings.AUTH_USER_MODEL, verbose_name='confirmed by')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='matches.match', verbose_name='match')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_scores', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_scores', to='accounts.playerprofile', verbose_name='winner')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
                'db_table': 'scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('tennis', 'Tennis'), ('padel', 'Padel')], max_length=20, verbose_name='sport')),
                ('points', models.IntegerField(default=1000, verbose_name='points')),
                ('wins', models.IntegerField(default=0, verbose_name='wins')),
                ('losses', models.IntegerField(default=0, verbose_name='losses')),
                ('rank_position', models.IntegerField(blank=True, null=True, verbose_name='rank position')),
                ('last_match_at', models.DateTimeField(blank=True, null=True, verbose_name='last match at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='accounts.playerprofile', verbose_name='player')),
            ],
            options={
                'verbose_name': 'ranking',
                'verbose_name_plural': 'rankings',
                'db_table': 'rankings',
                'ordering': ['-points'],
                'unique_together': {('player', 'sport')},
            },
        ),
    ]
