# Generated by Django 5.2.3 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('team_a', 'Team A'), ('team_b', 'Team B')], max_length=20, null=True, verbose_name='winning team'),
        ),
    ]
