# Generated by Django 5.2.3 on 2026-03-26 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_score_winning_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='admin note'),
        ),
        migrations.AddField(
            model_name='score',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_scores', to=settings.AUTH_USER_MODEL, verbose_name='resolved by'),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
