# Generated by Django 5.2.3 on 2026-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_playerprofile_idx_profile_city_and_more'),
        ('scoring', '0003_score_admin_resolve'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['sport', '-points'], name='idx_ranking_sport_pts'),
        ),
    ]
