# Generated by Django 5.2.3 on 2026-03-24 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='venue name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='website URL')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_venues', to=settings.AUTH_USER_MODEL, verbose_name='managed by')),
            ],
            options={
                'verbose_name': 'venue',
                'verbose_name_plural': 'venues',
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='court name')),
                ('sport', models.CharField(choices=[('tennis', 'Tennis'), ('padel', 'Padel')], max_length=20, verbose_name='sport')),
                ('surface', models.CharField(choices=[('clay', 'Clay'), ('hard', 'Hard'), ('grass', 'Grass'), ('artificial', 'Artificial')], max_length=20, verbose_name='surface')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='indoor')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='hourly rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='venues.venue', verbose_name='venue')),
            ],
            options={
                'verbose_name': 'court',
                'verbose_name_plural': 'courts',
                'db_table': 'courts',
                'ordering': ['venue', 'name'],
            },
        ),
    ]
