# Generated by Django 5.2.3 on 2026-03-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='booking_url',
            field=models.URLField(blank=True, null=True, verbose_name='booking URL'),
        ),
    ]
