# Generated by Django 5.2.3 on 2026-03-27 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_booking_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['status', 'date'], name='idx_slot_status_date'),
        ),
    ]
